"""Initial migration

Revision ID: 699e42859c40
Revises: 
Create Date: 2026-09-11 12:36:24.528193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699e42859c40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('platform_event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_events_event_time'), 'social_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_social_events_platform'), 'social_events', ['platform'], unique=False)
    op.create_index(op.f('ix_social_events_platform_event_id'), 'social_events', ['platform_event_id'], unique=True)
    op.create_index(op.f('ix_social_events_user_id'), 'social_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_events_user_id'), table_name='social_events')
    op.drop_index(op.f('ix_social_events_platform_event_id'), table_name='social_events')
    op.drop_index(op.f('ix_social_events_platform'), table_name='social_events')
    op.drop_index(op.f('ix_social_events_event_time'), table_name='social_events')
    op.drop_table('social_events')
    # ### end Alembic commands ###
